#!/usr/bin/env bash
set -e

# somehow network=host not working on mac
if [[ "$OSTYPE" == "darwin"* ]]; then
    docker-compose -f docker-compose.yaml -f docker-compose.mac.yaml up -d
else
    docker-compose up -d
fi

